server:
  port: 8080

spring:
  application:
    name: nichijo_dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.42.0.10:3306/db_nichijo_v2
    username: root
    password: ^H,DcSO9kl%

  redis:
    host: 10.42.0.10
    port: 6379
    database: 0
    password: ^H,DcSO9kl%

  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true

logging:
  level:
    org.cadmium.nichijo.mapper: debug

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql