version: "3.1"
services:
  redis:
    image: redis:6.2.7
    container_name: redis
    command:
      "redis-server /etc/redis/redis.conf"
    volumes:
      - ./data:/data
      - ./logs/redis.log:/logs/redis.log
      - ./conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"